.TH "scripts/docs/files/chapter4/src Directory Reference" 3 "C Programming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/docs/files/chapter4/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBreverse\&.c\fP"
.br
.RI "Reverses the digits of a two-digit number\&. "
.in -1c
