.TH "scripts/docs/files/chapter3/src Directory Reference" 3 "C Programming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/docs/files/chapter3/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaddfrac2\&.c\fP"
.br
.ti -1c
.RI "file \fBdates\&.c\fP"
.br
.ti -1c
.RI "file \fBisbn\&.c\fP"
.br
.ti -1c
.RI "file \fBreceipt\&.c\fP"
.br
.ti -1c
.RI "file \fBsquare\&.c\fP"
.br
.ti -1c
.RI "file \fBtelephone\&.c\fP"
.br
.in -1c
