.TH "scripts/docs/files/chapter2/src Directory Reference" 3 "C Programming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/docs/files/chapter2/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbills\&.c\fP"
.br
.RI "Distribute a certain amount of money using\&. "
.ti -1c
.RI "file \fBfastPolynom\&.c\fP"
.br
.ti -1c
.RI "file \fBhello\&.c\fP"
.br
.ti -1c
.RI "file \fBisphere\&.c\fP"
.br
.ti -1c
.RI "file \fBloan\&.c\fP"
.br
.ti -1c
.RI "file \fBpolynom\&.c\fP"
.br
.ti -1c
.RI "file \fBsphere\&.c\fP"
.br
.ti -1c
.RI "file \fBstars\&.c\fP"
.br
.ti -1c
.RI "file \fBtax\&.c\fP"
.br
.in -1c
