.TH "scripts/docs/files/chapter2/src/hello.c" 3 "C Programming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/docs/files/chapter2/src/hello.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void )"

.PP
Definition at line \fB5\fP of file \fBhello\&.c\fP\&.
.nf
6 {
7     printf("Hello World");
8     return 0;
9 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for C Programming from the source code\&.
