.TH "scripts/docs/files/chapter3/src/telephone.c" 3 "C Programming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/docs/files/chapter3/src/telephone.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void )"

.PP
Definition at line \fB7\fP of file \fBtelephone\&.c\fP\&.
.nf
8 {
9     int section1, section2, section3;
10 
11     printf("Enter phone number [ (xxx) xxx\-xxxx ]: ");
12     scanf("(%d) %d\-%d", &section1, &section2, &section3);
13 
14     printf("You entered %3\&.3d\&.%3\&.3d\&.%4\&.4d", section1, section2, section3);
15 
16     return 0;
17 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for C Programming from the source code\&.
